apiVersion: v1
data:
  backend-config.env: |
    PGUSER="admin"
    PGHOST="postgres"
    PGDATABASE="tasks"
    PGPORT=5432
    keycloak_url = "http://keycloak:8080"
    realm = "task-realm"
    client_id = "backend"
    client_secret = "**********"
kind: ConfigMap
metadata:
  namespace: tasks   
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend-config
