apiVersion: v1
data:
  ex-backend-config.env: |
    PGUSER=admin
    PGHOST=postgres
    PGDATABASE=tasks
    PGPORT=5432
kind: ConfigMap
metadata:
  namespace: tasks   
  creationTimestamp: null
  labels:
    io.kompose.service: express-backend
  name: express-backend-config