apiVersion: v1
data:
  kc-admin-password: YWRtaW4=
kind: Secret
metadata:
  namespace: tasks   
  creationTimestamp: null
  labels:
    io.kompose.service: kc-admin-password
  name: kc-admin-password
type: Opaque
