apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -o ../kubernetes-part
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -o ../kubernetes-part
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-part-db-network: "true"
        io.kompose.network/docker-part-frontend-network: "true"
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - start
            - --import-realm
          env:
            - name: KC_ADMIN
              value: admin
            - name: KC_ADMIN_PASSWORD
              value: admin
            - name: KC_DB
              value: postgres
            - name: KC_DB_PASSWORD
              value: password
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres:5432/tasks
            - name: KC_DB_USERNAME
              value: admin
            - name: KC_HOSTNAME
              value: localhost
            - name: KC_HTTP_ENABLED
              value: "true"
          image: olhaya/keycloak:multiarch
          livenessProbe:
            exec:
              command:
                - /opt/keycloak/bin/kc.sh
                - show-config
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          name: keycloak
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /opt/keycloak/data
              name: keycloak-data
      restartPolicy: Always
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
status: {}
