# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: keycloak-pv
#   labels:
#     io.kompose.service: keycloak-data
# spec:
#   capacity:
#     storage: 100Mi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: ""
#   hostPath:
#     path: /mnt/data/keycloak 
#   claimRef:
#     namespace: tasks        
#     name: keycloak-data



apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  labels:
    io.kompose.service: keycloak-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/keycloak
