apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    io.kompose.service: postgres-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/postgres  
  claimRef:
    namespace: tasks         
    name: postgres-data
